version: '2'

services:
  backend:
    build: ./backend/
    ports:
     - "8080:8080"
     - "3000:3000"
    volumes:
     - .:/backend
  vueapp:
    build: ./vueapp/
    ports:
     - "5000:5000"
    volumes:
     - .:/vueapp


# patientplatypusnest.azurecr.io/elmtree_vueapp
# patientplatypusnest.azurecr.io/elmtree_backend
